// COMPLETE JLPT N5 + N4 Vocabulary
// Format: [word, reading, romaji, english_meaning, part_of_speech, level]

const vocabulary = {

  // ────────────────────────────────────────────────────────────
  //  N5 – NOUNS
  // ────────────────────────────────────────────────────────────
  nouns_n5: [
    // People & Roles
    ["人", "ひと", "hito", "person, human", "Noun", "N5"],
    ["方", "かた", "kata", "person (polite)", "Noun", "N5"],
    ["子", "こ", "ko", "child", "Noun", "N5"],
    ["男", "おとこ", "otoko", "man, male", "Noun", "N5"],
    ["女", "おんな", "onna", "woman, female", "Noun", "N5"],
    ["男の人", "おとこのひと", "otoko no hito", "man", "Noun", "N5"],
    ["女の人", "おんなのひと", "onna no hito", "woman", "Noun", "N5"],
    ["男の子", "おとこのこ", "otoko no ko", "boy", "Noun", "N5"],
    ["女の子", "おんなのこ", "onna no ko", "girl", "Noun", "N5"],
    ["私", "わたし", "watashi", "I, me", "Noun", "N5"],
    ["あなた", "あなた", "anata", "you", "Noun", "N5"],
    ["彼", "かれ", "kare", "he, him, boyfriend", "Noun", "N5"],
    ["彼女", "かのじょ", "kanojo", "she, her, girlfriend", "Noun", "N5"],
    // Family
    ["家族", "かぞく", "kazoku", "family", "Noun", "N5"],
    ["父", "ちち", "chichi", "father (own)", "Noun", "N5"],
    ["母", "はは", "haha", "mother (own)", "Noun", "N5"],
    ["お父さん", "おとうさん", "otousan", "father (someone else's / polite)", "Noun", "N5"],
    ["お母さん", "おかあさん", "okaasan", "mother (someone else's / polite)", "Noun", "N5"],
    ["兄", "あに", "ani", "older brother (own)", "Noun", "N5"],
    ["姉", "あね", "ane", "older sister (own)", "Noun", "N5"],
    ["弟", "おとうと", "otouto", "younger brother (own)", "Noun", "N5"],
    ["妹", "いもうと", "imouto", "younger sister (own)", "Noun", "N5"],
    ["お兄さん", "おにいさん", "oniisan", "older brother (polite)", "Noun", "N5"],
    ["お姉さん", "おねえさん", "oneesan", "older sister (polite)", "Noun", "N5"],
    ["弟さん", "おとうとさん", "otouto-san", "younger brother (polite)", "Noun", "N5"],
    ["妹さん", "いもうとさん", "imouto-san", "younger sister (polite)", "Noun", "N5"],
    ["子供", "こども", "kodomo", "child, children", "Noun", "N5"],
    ["友達", "ともだち", "tomodachi", "friend", "Noun", "N5"],
    // Occupations / Roles
    ["先生", "せんせい", "sensei", "teacher", "Noun", "N5"],
    ["学生", "がくせい", "gakusei", "student", "Noun", "N5"],
    ["留学生", "りゅうがくせい", "ryuugakusei", "international student", "Noun", "N5"],
    ["会社員", "かいしゃいん", "kaishain", "company employee", "Noun", "N5"],
    ["医者", "いしゃ", "isha", "doctor", "Noun", "N5"],
    ["看護師", "かんごし", "kangoshi", "nurse", "Noun", "N5"],
    ["店員", "てんいん", "ten'in", "shop staff, store clerk", "Noun", "N5"],
    ["警官", "けいかん", "keikan", "police officer", "Noun", "N5"],
    ["銀行員", "ぎんこういん", "ginkouin", "bank employee", "Noun", "N5"],
    ["大学生", "だいがくせい", "daigakusei", "university student", "Noun", "N5"],
    // Places
    ["家", "いえ", "ie", "house, home", "Noun", "N5"],
    ["うち", "うち", "uchi", "home, house (casual)", "Noun", "N5"],
    ["部屋", "へや", "heya", "room", "Noun", "N5"],
    ["学校", "がっこう", "gakkou", "school", "Noun", "N5"],
    ["大学", "だいがく", "daigaku", "university", "Noun", "N5"],
    ["会社", "かいしゃ", "kaisha", "company, office", "Noun", "N5"],
    ["銀行", "ぎんこう", "ginkou", "bank", "Noun", "N5"],
    ["郵便局", "ゆうびんきょく", "yuubinkyoku", "post office", "Noun", "N5"],
    ["病院", "びょういん", "byouin", "hospital", "Noun", "N5"],
    ["図書館", "としょかん", "toshokan", "library", "Noun", "N5"],
    ["駅", "えき", "eki", "train station", "Noun", "N5"],
    ["空港", "くうこう", "kuukou", "airport", "Noun", "N5"],
    ["店", "みせ", "mise", "shop, store", "Noun", "N5"],
    ["レストラン", "レストラン", "resutoran", "restaurant", "Noun", "N5"],
    ["喫茶店", "きっさてん", "kissaten", "coffee shop, café", "Noun", "N5"],
    ["公園", "こうえん", "kouen", "park", "Noun", "N5"],
    ["デパート", "デパート", "depaato", "department store", "Noun", "N5"],
    ["スーパー", "スーパー", "suupaa", "supermarket", "Noun", "N5"],
    ["本屋", "ほんや", "hon'ya", "bookshop", "Noun", "N5"],
    ["花屋", "はなや", "hanaya", "flower shop", "Noun", "N5"],
    ["八百屋", "やおや", "yaoya", "greengrocer", "Noun", "N5"],
    ["肉屋", "にくや", "nikuya", "butcher", "Noun", "N5"],
    ["魚屋", "さかなや", "sakanaya", "fish shop", "Noun", "N5"],
    ["薬局", "やっきょく", "yakkyoku", "pharmacy", "Noun", "N5"],
    ["美容院", "びよういん", "biyouin", "beauty salon, hairdresser", "Noun", "N5"],
    ["トイレ", "トイレ", "toire", "toilet, restroom", "Noun", "N5"],
    ["玄関", "げんかん", "genkan", "entrance, front door", "Noun", "N5"],
    ["台所", "だいどころ", "daidokoro", "kitchen", "Noun", "N5"],
    ["お風呂", "おふろ", "ofuro", "bath, bathtub", "Noun", "N5"],
    ["庭", "にわ", "niwa", "garden, yard", "Noun", "N5"],
    ["階段", "かいだん", "kaidan", "stairs, staircase", "Noun", "N5"],
    ["廊下", "ろうか", "rouka", "hallway, corridor", "Noun", "N5"],
    // Transport
    ["電車", "でんしゃ", "densha", "train, electric train", "Noun", "N5"],
    ["地下鉄", "ちかてつ", "chikatetsu", "subway, metro", "Noun", "N5"],
    ["バス", "バス", "basu", "bus", "Noun", "N5"],
    ["タクシー", "タクシー", "takushii", "taxi", "Noun", "N5"],
    ["車", "くるま", "kuruma", "car, vehicle", "Noun", "N5"],
    ["自転車", "じてんしゃ", "jitensha", "bicycle", "Noun", "N5"],
    ["飛行機", "ひこうき", "hikouki", "airplane", "Noun", "N5"],
    ["船", "ふね", "fune", "ship, boat", "Noun", "N5"],
    ["バイク", "バイク", "baiku", "motorbike", "Noun", "N5"],
    ["切符", "きっぷ", "kippu", "ticket", "Noun", "N5"],
    // Food & Drink
    ["水", "みず", "mizu", "water", "Noun", "N5"],
    ["お茶", "おちゃ", "ocha", "green tea", "Noun", "N5"],
    ["コーヒー", "コーヒー", "koohii", "coffee", "Noun", "N5"],
    ["ジュース", "ジュース", "juusu", "juice", "Noun", "N5"],
    ["ビール", "ビール", "biiru", "beer", "Noun", "N5"],
    ["ご飯", "ごはん", "gohan", "cooked rice, meal", "Noun", "N5"],
    ["パン", "パン", "pan", "bread", "Noun", "N5"],
    ["肉", "にく", "niku", "meat", "Noun", "N5"],
    ["魚", "さかな", "sakana", "fish", "Noun", "N5"],
    ["野菜", "やさい", "yasai", "vegetable(s)", "Noun", "N5"],
    ["果物", "くだもの", "kudamono", "fruit", "Noun", "N5"],
    ["卵", "たまご", "tamago", "egg", "Noun", "N5"],
    ["牛乳", "ぎゅうにゅう", "gyuunyuu", "milk", "Noun", "N5"],
    ["塩", "しお", "shio", "salt", "Noun", "N5"],
    ["砂糖", "さとう", "satou", "sugar", "Noun", "N5"],
    ["醤油", "しょうゆ", "shouyu", "soy sauce", "Noun", "N5"],
    ["朝ご飯", "あさごはん", "asagohan", "breakfast", "Noun", "N5"],
    ["昼ご飯", "ひるごはん", "hirugohan", "lunch", "Noun", "N5"],
    ["晩ご飯", "ばんごはん", "bangohan", "dinner", "Noun", "N5"],
    ["弁当", "べんとう", "bentou", "packed lunch, bento", "Noun", "N5"],
    ["おかし", "おかし", "okashi", "sweets, snacks", "Noun", "N5"],
    ["寿司", "すし", "sushi", "sushi", "Noun", "N5"],
    ["天ぷら", "てんぷら", "tenpura", "tempura", "Noun", "N5"],
    ["ラーメン", "ラーメン", "raamen", "ramen noodles", "Noun", "N5"],
    ["そば", "そば", "soba", "soba noodles", "Noun", "N5"],
    ["うどん", "うどん", "udon", "udon noodles", "Noun", "N5"],
    ["メニュー", "メニュー", "menyuu", "menu", "Noun", "N5"],
    // Objects & Items
    ["本", "ほん", "hon", "book", "Noun", "N5"],
    ["雑誌", "ざっし", "zasshi", "magazine", "Noun", "N5"],
    ["新聞", "しんぶん", "shinbun", "newspaper", "Noun", "N5"],
    ["手紙", "てがみ", "tegami", "letter (written)", "Noun", "N5"],
    ["電話", "でんわ", "denwa", "telephone", "Noun", "N5"],
    ["テレビ", "テレビ", "terebi", "television, TV", "Noun", "N5"],
    ["ラジオ", "ラジオ", "rajio", "radio", "Noun", "N5"],
    ["カメラ", "カメラ", "kamera", "camera", "Noun", "N5"],
    ["パソコン", "パソコン", "pasokon", "personal computer, PC", "Noun", "N5"],
    ["かばん", "かばん", "kaban", "bag, briefcase", "Noun", "N5"],
    ["財布", "さいふ", "saifu", "wallet, purse", "Noun", "N5"],
    ["鍵", "かぎ", "kagi", "key, lock", "Noun", "N5"],
    ["傘", "かさ", "kasa", "umbrella", "Noun", "N5"],
    ["眼鏡", "めがね", "megane", "glasses, spectacles", "Noun", "N5"],
    ["時計", "とけい", "tokei", "clock, watch", "Noun", "N5"],
    ["机", "つくえ", "tsukue", "desk", "Noun", "N5"],
    ["椅子", "いす", "isu", "chair", "Noun", "N5"],
    ["窓", "まど", "mado", "window", "Noun", "N5"],
    ["ドア", "ドア", "doa", "door", "Noun", "N5"],
    ["電気", "でんき", "denki", "electricity, light", "Noun", "N5"],
    ["ペン", "ペン", "pen", "pen", "Noun", "N5"],
    ["ボールペン", "ボールペン", "boorupen", "ballpoint pen", "Noun", "N5"],
    ["鉛筆", "えんぴつ", "enpitsu", "pencil", "Noun", "N5"],
    ["ノート", "ノート", "nooto", "notebook", "Noun", "N5"],
    ["紙", "かみ", "kami", "paper", "Noun", "N5"],
    ["写真", "しゃしん", "shashin", "photograph, photo", "Noun", "N5"],
    ["花", "はな", "hana", "flower", "Noun", "N5"],
    ["木", "き", "ki", "tree, wood", "Noun", "N5"],
    ["石", "いし", "ishi", "stone, rock", "Noun", "N5"],
    ["お金", "おかね", "okane", "money", "Noun", "N5"],
    ["値段", "ねだん", "nedan", "price, cost", "Noun", "N5"],
    ["プレゼント", "プレゼント", "purezento", "present, gift", "Noun", "N5"],
    ["テープ", "テープ", "teepu", "tape", "Noun", "N5"],
    ["はさみ", "はさみ", "hasami", "scissors", "Noun", "N5"],
    // Clothing
    ["服", "ふく", "fuku", "clothes, clothing", "Noun", "N5"],
    ["シャツ", "シャツ", "shatsu", "shirt", "Noun", "N5"],
    ["ズボン", "ズボン", "zubon", "trousers, pants", "Noun", "N5"],
    ["スカート", "スカート", "sukaato", "skirt", "Noun", "N5"],
    ["コート", "コート", "kooto", "coat", "Noun", "N5"],
    ["セーター", "セーター", "seetaa", "sweater, jumper", "Noun", "N5"],
    ["ジャケット", "ジャケット", "jaketto", "jacket", "Noun", "N5"],
    ["帽子", "ぼうし", "boushi", "hat, cap", "Noun", "N5"],
    ["靴", "くつ", "kutsu", "shoes", "Noun", "N5"],
    ["靴下", "くつした", "kutsushita", "socks", "Noun", "N5"],
    ["ネクタイ", "ネクタイ", "nekutai", "necktie", "Noun", "N5"],
    ["ワンピース", "ワンピース", "wanpiisu", "dress (one-piece)", "Noun", "N5"],
    // Nature & Weather
    ["天気", "てんき", "tenki", "weather", "Noun", "N5"],
    ["空", "そら", "sora", "sky", "Noun", "N5"],
    ["雨", "あめ", "ame", "rain", "Noun", "N5"],
    ["雪", "ゆき", "yuki", "snow", "Noun", "N5"],
    ["風", "かぜ", "kaze", "wind", "Noun", "N5"],
    ["太陽", "たいよう", "taiyou", "sun", "Noun", "N5"],
    ["月", "つき", "tsuki", "moon", "Noun", "N5"],
    ["星", "ほし", "hoshi", "star", "Noun", "N5"],
    ["山", "やま", "yama", "mountain", "Noun", "N5"],
    ["川", "かわ", "kawa", "river", "Noun", "N5"],
    ["海", "うみ", "umi", "sea, ocean", "Noun", "N5"],
    ["池", "いけ", "ike", "pond", "Noun", "N5"],
    ["森", "もり", "mori", "forest", "Noun", "N5"],
    ["草", "くさ", "kusa", "grass", "Noun", "N5"],
    // Time & Calendar
    ["時間", "じかん", "jikan", "time, hours", "Noun", "N5"],
    ["分", "ふん", "fun", "minute", "Noun", "N5"],
    ["秒", "びょう", "byou", "second (time)", "Noun", "N5"],
    ["今", "いま", "ima", "now, currently", "Noun", "N5"],
    ["今日", "きょう", "kyou", "today", "Noun", "N5"],
    ["明日", "あした", "ashita", "tomorrow", "Noun", "N5"],
    ["明後日", "あさって", "asatte", "day after tomorrow", "Noun", "N5"],
    ["昨日", "きのう", "kinou", "yesterday", "Noun", "N5"],
    ["一昨日", "おととい", "ototoi", "day before yesterday", "Noun", "N5"],
    ["朝", "あさ", "asa", "morning", "Noun", "N5"],
    ["昼", "ひる", "hiru", "daytime, noon", "Noun", "N5"],
    ["夜", "よる", "yoru", "night, evening", "Noun", "N5"],
    ["午前", "ごぜん", "gozen", "AM, morning", "Noun", "N5"],
    ["午後", "ごご", "gogo", "PM, afternoon", "Noun", "N5"],
    ["今週", "こんしゅう", "konshuu", "this week", "Noun", "N5"],
    ["来週", "らいしゅう", "raishuu", "next week", "Noun", "N5"],
    ["先週", "せんしゅう", "senshuu", "last week", "Noun", "N5"],
    ["今月", "こんげつ", "kongetsu", "this month", "Noun", "N5"],
    ["来月", "らいげつ", "raigetsu", "next month", "Noun", "N5"],
    ["先月", "せんげつ", "sengetsu", "last month", "Noun", "N5"],
    ["今年", "ことし", "kotoshi", "this year", "Noun", "N5"],
    ["来年", "らいねん", "rainen", "next year", "Noun", "N5"],
    ["去年", "きょねん", "kyonen", "last year", "Noun", "N5"],
    ["毎日", "まいにち", "mainichi", "every day", "Noun", "N5"],
    ["毎週", "まいしゅう", "maishuu", "every week", "Noun", "N5"],
    ["毎月", "まいつき", "maitsuki", "every month", "Noun", "N5"],
    ["毎年", "まいとし", "maitoshi", "every year", "Noun", "N5"],
    ["週末", "しゅうまつ", "shuumatsu", "weekend", "Noun", "N5"],
    ["平日", "へいじつ", "heijitsu", "weekday", "Noun", "N5"],
    // Days of week
    ["月曜日", "げつようび", "getsuyoubi", "Monday", "Noun", "N5"],
    ["火曜日", "かようび", "kayoubi", "Tuesday", "Noun", "N5"],
    ["水曜日", "すいようび", "suiyoubi", "Wednesday", "Noun", "N5"],
    ["木曜日", "もくようび", "mokuyoubi", "Thursday", "Noun", "N5"],
    ["金曜日", "きんようび", "kin'youbi", "Friday", "Noun", "N5"],
    ["土曜日", "どようび", "doyoubi", "Saturday", "Noun", "N5"],
    ["日曜日", "にちようび", "nichiyoubi", "Sunday", "Noun", "N5"],
    // Months
    ["一月", "いちがつ", "ichigatsu", "January", "Noun", "N5"],
    ["二月", "にがつ", "nigatsu", "February", "Noun", "N5"],
    ["三月", "さんがつ", "sangatsu", "March", "Noun", "N5"],
    ["四月", "しがつ", "shigatsu", "April", "Noun", "N5"],
    ["五月", "ごがつ", "gogatsu", "May", "Noun", "N5"],
    ["六月", "ろくがつ", "rokugatsu", "June", "Noun", "N5"],
    ["七月", "しちがつ", "shichigatsu", "July", "Noun", "N5"],
    ["八月", "はちがつ", "hachigatsu", "August", "Noun", "N5"],
    ["九月", "くがつ", "kugatsu", "September", "Noun", "N5"],
    ["十月", "じゅうがつ", "juugatsu", "October", "Noun", "N5"],
    ["十一月", "じゅういちがつ", "juuichigatsu", "November", "Noun", "N5"],
    ["十二月", "じゅうにがつ", "juunigatsu", "December", "Noun", "N5"],
    // Misc Nouns
    ["名前", "なまえ", "namae", "name", "Noun", "N5"],
    ["言葉", "ことば", "kotoba", "word, language", "Noun", "N5"],
    ["日本語", "にほんご", "nihongo", "Japanese language", "Noun", "N5"],
    ["英語", "えいご", "eigo", "English language", "Noun", "N5"],
    ["国", "くに", "kuni", "country, nation", "Noun", "N5"],
    ["日本", "にほん", "nihon", "Japan", "Noun", "N5"],
    ["仕事", "しごと", "shigoto", "work, job", "Noun", "N5"],
    ["授業", "じゅぎょう", "jugyou", "class, lesson", "Noun", "N5"],
    ["音楽", "おんがく", "ongaku", "music", "Noun", "N5"],
    ["映画", "えいが", "eiga", "movie, film", "Noun", "N5"],
    ["スポーツ", "スポーツ", "supootsu", "sport(s)", "Noun", "N5"],
    ["旅行", "りょこう", "ryokou", "travel, trip", "Noun", "N5"],
    ["休み", "やすみ", "yasumi", "rest, holiday, day off", "Noun", "N5"],
    ["誕生日", "たんじょうび", "tanjoubi", "birthday", "Noun", "N5"],
    ["色", "いろ", "iro", "colour", "Noun", "N5"],
    ["問題", "もんだい", "mondai", "problem, question", "Noun", "N5"],
    ["答え", "こたえ", "kotae", "answer, response", "Noun", "N5"],
    ["意味", "いみ", "imi", "meaning", "Noun", "N5"],
    ["所", "ところ", "tokoro", "place, spot", "Noun", "N5"],
    ["こと", "こと", "koto", "thing (abstract), matter", "Noun", "N5"],
    ["もの", "もの", "mono", "thing (physical), object", "Noun", "N5"],
    ["時", "とき", "toki", "time, moment, occasion", "Noun", "N5"],
    ["中", "なか", "naka", "inside, middle", "Noun", "N5"],
    ["上", "うえ", "ue", "above, top, up", "Noun", "N5"],
    ["下", "した", "shita", "below, bottom, under", "Noun", "N5"],
    ["前", "まえ", "mae", "front, before", "Noun", "N5"],
    ["後ろ", "うしろ", "ushiro", "behind, back", "Noun", "N5"],
    ["右", "みぎ", "migi", "right (direction)", "Noun", "N5"],
    ["左", "ひだり", "hidari", "left (direction)", "Noun", "N5"],
    ["横", "よこ", "yoko", "side, horizontal", "Noun", "N5"],
    ["隣", "となり", "tonari", "next to, neighbouring", "Noun", "N5"],
    ["間", "あいだ", "aida", "between, among, interval", "Noun", "N5"],
    // Proper nouns
    ["アメリカ", "アメリカ", "Amerika", "America, USA", "Noun", "N5"],
    ["イギリス", "イギリス", "Igirisu", "United Kingdom", "Noun", "N5"],
    ["フランス", "フランス", "Furansu", "France", "Noun", "N5"],
    ["ドイツ", "ドイツ", "Doitsu", "Germany", "Noun", "N5"],
    ["中国", "ちゅうごく", "Chuugoku", "China", "Noun", "N5"],
    ["韓国", "かんこく", "Kankoku", "South Korea", "Noun", "N5"],
    ["東京", "とうきょう", "Toukyou", "Tokyo", "Noun", "N5"],
    ["大阪", "おおさか", "Oosaka", "Osaka", "Noun", "N5"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N4 – NOUNS
  // ────────────────────────────────────────────────────────────
  nouns_n4: [
    // People & Society
    ["大人", "おとな", "otona", "adult", "Noun", "N4"],
    ["若者", "わかもの", "wakamono", "young person, youth", "Noun", "N4"],
    ["老人", "ろうじん", "roujin", "elderly person", "Noun", "N4"],
    ["夫", "おっと", "otto", "husband (own)", "Noun", "N4"],
    ["妻", "つま", "tsuma", "wife (own)", "Noun", "N4"],
    ["ご主人", "ごしゅじん", "goshujin", "husband (polite)", "Noun", "N4"],
    ["奥さん", "おくさん", "okusan", "wife (polite)", "Noun", "N4"],
    ["親", "おや", "oya", "parent(s)", "Noun", "N4"],
    ["祖父", "そふ", "sofu", "grandfather (own)", "Noun", "N4"],
    ["祖母", "そぼ", "sobo", "grandmother (own)", "Noun", "N4"],
    ["おじいさん", "おじいさん", "ojiisan", "grandfather (polite/general)", "Noun", "N4"],
    ["おばあさん", "おばあさん", "obaasan", "grandmother (polite/general)", "Noun", "N4"],
    ["親戚", "しんせき", "shinseki", "relative(s)", "Noun", "N4"],
    ["知り合い", "しりあい", "shiriai", "acquaintance", "Noun", "N4"],
    ["隣人", "りんじん", "rinjin", "neighbour", "Noun", "N4"],
    ["客", "きゃく", "kyaku", "guest, customer, visitor", "Noun", "N4"],
    ["外国人", "がいこくじん", "gaikokujin", "foreigner, non-Japanese person", "Noun", "N4"],
    // Work & Occupations
    ["社長", "しゃちょう", "shachou", "company president, CEO", "Noun", "N4"],
    ["部長", "ぶちょう", "buchou", "department head, manager", "Noun", "N4"],
    ["運転手", "うんてんしゅ", "untenshu", "driver", "Noun", "N4"],
    ["料理人", "りょうりにん", "ryourinin", "cook, chef", "Noun", "N4"],
    ["歌手", "かしゅ", "kashu", "singer", "Noun", "N4"],
    ["俳優", "はいゆう", "haiyuu", "actor, actress", "Noun", "N4"],
    ["作家", "さっか", "sakka", "writer, author", "Noun", "N4"],
    ["科学者", "かがくしゃ", "kagakusha", "scientist", "Noun", "N4"],
    ["政治家", "せいじか", "seijika", "politician", "Noun", "N4"],
    ["農家", "のうか", "nouka", "farmer, farming household", "Noun", "N4"],
    ["アルバイト", "アルバイト", "arubaito", "part-time job", "Noun", "N4"],
    // Education
    ["宿題", "しゅくだい", "shukudai", "homework", "Noun", "N4"],
    ["試験", "しけん", "shiken", "exam, test", "Noun", "N4"],
    ["テスト", "テスト", "tesuto", "test, quiz", "Noun", "N4"],
    ["入学", "にゅうがく", "nyuugaku", "school enrolment", "Noun", "N4"],
    ["卒業", "そつぎょう", "sotsugyou", "graduation", "Noun", "N4"],
    ["留学", "りゅうがく", "ryuugaku", "studying abroad", "Noun", "N4"],
    ["練習", "れんしゅう", "renshuu", "practice, exercise", "Noun", "N4"],
    ["説明", "せつめい", "setsumei", "explanation", "Noun", "N4"],
    ["文章", "ぶんしょう", "bunshou", "text, writing, sentence", "Noun", "N4"],
    ["作文", "さくぶん", "sakubun", "composition, written essay", "Noun", "N4"],
    ["辞書", "じしょ", "jisho", "dictionary", "Noun", "N4"],
    ["教科書", "きょうかしょ", "kyoukasho", "textbook", "Noun", "N4"],
    ["成績", "せいせき", "seiseki", "grades, academic results", "Noun", "N4"],
    ["合格", "ごうかく", "goukaku", "passing (an exam)", "Noun", "N4"],
    // Work / Office
    ["会議", "かいぎ", "kaigi", "meeting, conference", "Noun", "N4"],
    ["出張", "しゅっちょう", "shucchou", "business trip", "Noun", "N4"],
    ["給料", "きゅうりょう", "kyuuryou", "salary, wages", "Noun", "N4"],
    ["残業", "ざんぎょう", "zangyou", "overtime work", "Noun", "N4"],
    ["工場", "こうじょう", "koujou", "factory", "Noun", "N4"],
    ["経済", "けいざい", "keizai", "economy, economics", "Noun", "N4"],
    ["政治", "せいじ", "seiji", "politics", "Noun", "N4"],
    ["貿易", "ぼうえき", "boueki", "trade (international)", "Noun", "N4"],
    // Health & Body
    ["体", "からだ", "karada", "body", "Noun", "N4"],
    ["頭", "あたま", "atama", "head, brain", "Noun", "N4"],
    ["顔", "かお", "kao", "face", "Noun", "N4"],
    ["目", "め", "me", "eye", "Noun", "N4"],
    ["鼻", "はな", "hana", "nose", "Noun", "N4"],
    ["耳", "みみ", "mimi", "ear", "Noun", "N4"],
    ["口", "くち", "kuchi", "mouth", "Noun", "N4"],
    ["歯", "は", "ha", "tooth, teeth", "Noun", "N4"],
    ["首", "くび", "kubi", "neck", "Noun", "N4"],
    ["肩", "かた", "kata", "shoulder", "Noun", "N4"],
    ["腕", "うで", "ude", "arm", "Noun", "N4"],
    ["手", "て", "te", "hand", "Noun", "N4"],
    ["指", "ゆび", "yubi", "finger, toe", "Noun", "N4"],
    ["胸", "むね", "mune", "chest, breast", "Noun", "N4"],
    ["背中", "せなか", "senaka", "back (of body)", "Noun", "N4"],
    ["腹", "はら", "hara", "stomach, belly", "Noun", "N4"],
    ["足", "あし", "ashi", "leg, foot", "Noun", "N4"],
    ["ひざ", "ひざ", "hiza", "knee", "Noun", "N4"],
    ["病気", "びょうき", "byouki", "illness, disease", "Noun", "N4"],
    ["風邪", "かぜ", "kaze", "cold (illness)", "Noun", "N4"],
    ["熱", "ねつ", "netsu", "fever, heat", "Noun", "N4"],
    ["痛み", "いたみ", "itami", "pain, ache", "Noun", "N4"],
    ["薬", "くすり", "kusuri", "medicine, drug", "Noun", "N4"],
    ["入院", "にゅういん", "nyuuin", "hospital admission", "Noun", "N4"],
    ["退院", "たいいん", "taiin", "discharge from hospital", "Noun", "N4"],
    ["手術", "しゅじゅつ", "shujutsu", "surgery, operation", "Noun", "N4"],
    ["注射", "ちゅうしゃ", "chuusha", "injection, shot", "Noun", "N4"],
    // Nature & Environment
    ["自然", "しぜん", "shizen", "nature", "Noun", "N4"],
    ["気候", "きこう", "kikou", "climate", "Noun", "N4"],
    ["季節", "きせつ", "kisetsu", "season", "Noun", "N4"],
    ["春", "はる", "haru", "spring", "Noun", "N4"],
    ["夏", "なつ", "natsu", "summer", "Noun", "N4"],
    ["秋", "あき", "aki", "autumn, fall", "Noun", "N4"],
    ["冬", "ふゆ", "fuyu", "winter", "Noun", "N4"],
    ["空気", "くうき", "kuuki", "air, atmosphere", "Noun", "N4"],
    ["動物", "どうぶつ", "doubutsu", "animal", "Noun", "N4"],
    ["植物", "しょくぶつ", "shokubutsu", "plant", "Noun", "N4"],
    ["鳥", "とり", "tori", "bird", "Noun", "N4"],
    ["虫", "むし", "mushi", "insect, bug", "Noun", "N4"],
    ["犬", "いぬ", "inu", "dog", "Noun", "N4"],
    ["猫", "ねこ", "neko", "cat", "Noun", "N4"],
    ["地震", "じしん", "jishin", "earthquake", "Noun", "N4"],
    ["台風", "たいふう", "taifuu", "typhoon", "Noun", "N4"],
    ["洪水", "こうずい", "kouzui", "flood", "Noun", "N4"],
    ["火事", "かじ", "kaji", "fire (disaster)", "Noun", "N4"],
    ["環境", "かんきょう", "kankyou", "environment", "Noun", "N4"],
    ["汚染", "おせん", "osen", "pollution, contamination", "Noun", "N4"],
    // Abstract / Concepts
    ["意見", "いけん", "iken", "opinion, view", "Noun", "N4"],
    ["理由", "りゆう", "riyuu", "reason, cause", "Noun", "N4"],
    ["目的", "もくてき", "mokuteki", "purpose, goal, aim", "Noun", "N4"],
    ["方法", "ほうほう", "houhou", "method, way", "Noun", "N4"],
    ["計画", "けいかく", "keikaku", "plan, project", "Noun", "N4"],
    ["準備", "じゅんび", "junbi", "preparation", "Noun", "N4"],
    ["経験", "けいけん", "keiken", "experience", "Noun", "N4"],
    ["気持ち", "きもち", "kimochi", "feeling, mood", "Noun", "N4"],
    ["性格", "せいかく", "seikaku", "personality, character", "Noun", "N4"],
    ["習慣", "しゅうかん", "shuukan", "habit, custom", "Noun", "N4"],
    ["文化", "ぶんか", "bunka", "culture", "Noun", "N4"],
    ["社会", "しゃかい", "shakai", "society", "Noun", "N4"],
    ["生活", "せいかつ", "seikatsu", "life, lifestyle, living", "Noun", "N4"],
    ["関係", "かんけい", "kankei", "relationship, connection", "Noun", "N4"],
    ["影響", "えいきょう", "eikyou", "influence, effect", "Noun", "N4"],
    ["結果", "けっか", "kekka", "result, outcome", "Noun", "N4"],
    ["原因", "げんいん", "gen'in", "cause, origin", "Noun", "N4"],
    ["条件", "じょうけん", "jouken", "condition, requirement", "Noun", "N4"],
    ["夢", "ゆめ", "yume", "dream", "Noun", "N4"],
    ["希望", "きぼう", "kibou", "hope, wish", "Noun", "N4"],
    ["心配", "しんぱい", "shinpai", "worry, concern", "Noun", "N4"],
    ["努力", "どりょく", "doryoku", "effort, hard work", "Noun", "N4"],
    ["成功", "せいこう", "seikou", "success", "Noun", "N4"],
    ["失敗", "しっぱい", "shippai", "failure, mistake", "Noun", "N4"],
    ["目標", "もくひょう", "mokuhyou", "goal, target", "Noun", "N4"],
    ["記憶", "きおく", "kioku", "memory, recollection", "Noun", "N4"],
    ["想像", "そうぞう", "souzou", "imagination", "Noun", "N4"],
    // Places & Geography
    ["場所", "ばしょ", "basho", "place, location", "Noun", "N4"],
    ["地図", "ちず", "chizu", "map", "Noun", "N4"],
    ["方向", "ほうこう", "houkou", "direction", "Noun", "N4"],
    ["道", "みち", "michi", "road, street, path", "Noun", "N4"],
    ["交通", "こうつう", "koutsuu", "traffic, transportation", "Noun", "N4"],
    ["信号", "しんごう", "shingou", "traffic light, signal", "Noun", "N4"],
    ["橋", "はし", "hashi", "bridge", "Noun", "N4"],
    ["港", "みなと", "minato", "harbour, port", "Noun", "N4"],
    ["田舎", "いなか", "inaka", "countryside, rural area", "Noun", "N4"],
    ["都市", "とし", "toshi", "city, urban area", "Noun", "N4"],
    ["地域", "ちいき", "chiiki", "area, region", "Noun", "N4"],
    ["世界", "せかい", "sekai", "world", "Noun", "N4"],
    ["外国", "がいこく", "gaikoku", "foreign country", "Noun", "N4"],
    ["国際", "こくさい", "kokusai", "international", "Noun", "N4"],
    ["町", "まち", "machi", "town, neighbourhood", "Noun", "N4"],
    ["村", "むら", "mura", "village", "Noun", "N4"],
    // Things & Objects
    ["荷物", "にもつ", "nimotsu", "luggage, baggage", "Noun", "N4"],
    ["道具", "どうぐ", "dougu", "tool, instrument", "Noun", "N4"],
    ["機械", "きかい", "kikai", "machine, machinery", "Noun", "N4"],
    ["材料", "ざいりょう", "zairyou", "material, ingredient", "Noun", "N4"],
    ["ごみ", "ごみ", "gomi", "rubbish, garbage, trash", "Noun", "N4"],
    ["鏡", "かがみ", "kagami", "mirror", "Noun", "N4"],
    ["引き出し", "ひきだし", "hikidashi", "drawer", "Noun", "N4"],
    ["棚", "たな", "tana", "shelf", "Noun", "N4"],
    ["ふとん", "ふとん", "futon", "futon, Japanese bedding", "Noun", "N4"],
    ["押し入れ", "おしいれ", "oshiire", "Japanese-style closet", "Noun", "N4"],
    ["冷蔵庫", "れいぞうこ", "reizouko", "refrigerator", "Noun", "N4"],
    ["洗濯機", "せんたくき", "sentakuki", "washing machine", "Noun", "N4"],
    ["エアコン", "エアコン", "eakon", "air conditioner", "Noun", "N4"],
    ["エレベーター", "エレベーター", "erebeetaa", "elevator, lift", "Noun", "N4"],
    ["エスカレーター", "エスカレーター", "esukareetaa", "escalator", "Noun", "N4"],
    // Events & Activities
    ["パーティー", "パーティー", "paatii", "party", "Noun", "N4"],
    ["結婚式", "けっこんしき", "kekkonshiki", "wedding ceremony", "Noun", "N4"],
    ["葬式", "そうしき", "soushiki", "funeral", "Noun", "N4"],
    ["祭り", "まつり", "matsuri", "festival", "Noun", "N4"],
    ["コンサート", "コンサート", "konsaato", "concert", "Noun", "N4"],
    ["試合", "しあい", "shiai", "match, game, competition", "Noun", "N4"],
    ["運動会", "うんどうかい", "undoukai", "sports day, athletic meet", "Noun", "N4"],
    // Communication & Media
    ["ニュース", "ニュース", "nyuusu", "news", "Noun", "N4"],
    ["インターネット", "インターネット", "intaanetto", "internet", "Noun", "N4"],
    ["メール", "メール", "meeru", "email, message", "Noun", "N4"],
    ["広告", "こうこく", "koukoku", "advertisement", "Noun", "N4"],
    ["番組", "ばんぐみ", "bangumi", "TV/radio programme", "Noun", "N4"],
    ["歌", "うた", "uta", "song", "Noun", "N4"],
    ["絵", "え", "e", "painting, picture, drawing", "Noun", "N4"],
    ["芸術", "げいじゅつ", "geijutsu", "art", "Noun", "N4"],
    // Food (N4 additions)
    ["料理", "りょうり", "ryouri", "cooking, dish, cuisine", "Noun", "N4"],
    ["食事", "しょくじ", "shokuji", "meal, dining", "Noun", "N4"],
    ["レシピ", "レシピ", "reshipi", "recipe", "Noun", "N4"],
    ["お酒", "おさけ", "osake", "alcohol, sake", "Noun", "N4"],
    ["ワイン", "ワイン", "wain", "wine", "Noun", "N4"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N5 – VERBS
  // ────────────────────────────────────────────────────────────
  verbs_n5: [
    // Motion
    ["行く", "いく", "iku", "to go", "Verb", "N5"],
    ["来る", "くる", "kuru", "to come", "Verb", "N5"],
    ["帰る", "かえる", "kaeru", "to return, to go home", "Verb", "N5"],
    ["歩く", "あるく", "aruku", "to walk", "Verb", "N5"],
    ["走る", "はしる", "hashiru", "to run", "Verb", "N5"],
    ["乗る", "のる", "noru", "to ride, to get on (vehicle)", "Verb", "N5"],
    ["降りる", "おりる", "oriru", "to get off, to descend", "Verb", "N5"],
    ["入る", "はいる", "hairu", "to enter, to go in", "Verb", "N5"],
    ["出る", "でる", "deru", "to exit, to leave, to come out", "Verb", "N5"],
    ["上がる", "あがる", "agaru", "to go up, to rise", "Verb", "N5"],
    ["渡る", "わたる", "wataru", "to cross, to go across", "Verb", "N5"],
    ["曲がる", "まがる", "magaru", "to turn, to bend", "Verb", "N5"],
    ["止まる", "とまる", "tomaru", "to stop, to park", "Verb", "N5"],
    ["通る", "とおる", "tooru", "to pass through, to go along", "Verb", "N5"],
    // Daily Actions
    ["食べる", "たべる", "taberu", "to eat", "Verb", "N5"],
    ["飲む", "のむ", "nomu", "to drink", "Verb", "N5"],
    ["起きる", "おきる", "okiru", "to wake up, to get up", "Verb", "N5"],
    ["寝る", "ねる", "neru", "to sleep, to go to bed", "Verb", "N5"],
    ["着る", "きる", "kiru", "to wear (clothing)", "Verb", "N5"],
    ["脱ぐ", "ぬぐ", "nugu", "to take off (clothing)", "Verb", "N5"],
    ["履く", "はく", "haku", "to put on (shoes, trousers)", "Verb", "N5"],
    ["洗う", "あらう", "arau", "to wash", "Verb", "N5"],
    ["掃除する", "そうじする", "souji suru", "to clean, to tidy up", "Verb", "N5"],
    ["洗濯する", "せんたくする", "sentaku suru", "to do laundry", "Verb", "N5"],
    ["料理する", "りょうりする", "ryouri suru", "to cook", "Verb", "N5"],
    ["買う", "かう", "kau", "to buy", "Verb", "N5"],
    ["使う", "つかう", "tsukau", "to use", "Verb", "N5"],
    ["開ける", "あける", "akeru", "to open (something)", "Verb", "N5"],
    ["閉める", "しめる", "shimeru", "to close, to shut (something)", "Verb", "N5"],
    ["つける", "つける", "tsukeru", "to turn on (light, etc.)", "Verb", "N5"],
    ["消す", "けす", "kesu", "to turn off, to erase, to put out", "Verb", "N5"],
    ["休む", "やすむ", "yasumu", "to rest, to take a day off", "Verb", "N5"],
    ["働く", "はたらく", "hataraku", "to work, to be employed", "Verb", "N5"],
    ["遊ぶ", "あそぶ", "asobu", "to play, to enjoy oneself", "Verb", "N5"],
    ["泳ぐ", "およぐ", "oyogu", "to swim", "Verb", "N5"],
    ["切る", "きる", "kiru", "to cut", "Verb", "N5"],
    ["作る", "つくる", "tsukuru", "to make, to create", "Verb", "N5"],
    ["撮る", "とる", "toru", "to take (a photo)", "Verb", "N5"],
    ["吸う", "すう", "suu", "to inhale, to smoke (cigarette)", "Verb", "N5"],
    ["弾く", "ひく", "hiku", "to play (piano/guitar)", "Verb", "N5"],
    ["歌う", "うたう", "utau", "to sing", "Verb", "N5"],
    ["踊る", "おどる", "odoru", "to dance", "Verb", "N5"],
    ["浴びる", "あびる", "abiru", "to shower, to bathe in", "Verb", "N5"],
    ["磨く", "みがく", "migaku", "to polish, to brush (teeth)", "Verb", "N5"],
    // Communication & Cognition
    ["見る", "みる", "miru", "to see, to watch, to look", "Verb", "N5"],
    ["聞く", "きく", "kiku", "to listen, to hear, to ask", "Verb", "N5"],
    ["話す", "はなす", "hanasu", "to speak, to talk", "Verb", "N5"],
    ["読む", "よむ", "yomu", "to read", "Verb", "N5"],
    ["書く", "かく", "kaku", "to write", "Verb", "N5"],
    ["言う", "いう", "iu", "to say, to tell", "Verb", "N5"],
    ["分かる", "わかる", "wakaru", "to understand", "Verb", "N5"],
    ["知る", "しる", "shiru", "to know, to find out", "Verb", "N5"],
    ["思う", "おもう", "omou", "to think, to feel, to believe", "Verb", "N5"],
    ["教える", "おしえる", "oshieru", "to teach, to tell, to inform", "Verb", "N5"],
    ["習う", "ならう", "narau", "to learn (from someone)", "Verb", "N5"],
    ["勉強する", "べんきょうする", "benkyou suru", "to study", "Verb", "N5"],
    ["見せる", "みせる", "miseru", "to show", "Verb", "N5"],
    // Existence, Giving & Receiving
    ["ある", "ある", "aru", "to exist, to have (inanimate)", "Verb", "N5"],
    ["いる", "いる", "iru", "to exist, to be (animate)", "Verb", "N5"],
    ["する", "する", "suru", "to do", "Verb", "N5"],
    ["なる", "なる", "naru", "to become", "Verb", "N5"],
    ["できる", "できる", "dekiru", "to be able to, to be completed", "Verb", "N5"],
    ["もらう", "もらう", "morau", "to receive (from)", "Verb", "N5"],
    ["くれる", "くれる", "kureru", "to give (to me/us)", "Verb", "N5"],
    ["あげる", "あげる", "ageru", "to give (to someone)", "Verb", "N5"],
    ["持つ", "もつ", "motsu", "to hold, to have, to carry", "Verb", "N5"],
    ["置く", "おく", "oku", "to put, to place, to leave", "Verb", "N5"],
    ["取る", "とる", "toru", "to take, to pick up, to get", "Verb", "N5"],
    ["貸す", "かす", "kasu", "to lend", "Verb", "N5"],
    ["借りる", "かりる", "kariru", "to borrow", "Verb", "N5"],
    ["会う", "あう", "au", "to meet", "Verb", "N5"],
    ["待つ", "まつ", "matsu", "to wait", "Verb", "N5"],
    ["呼ぶ", "よぶ", "yobu", "to call, to invite", "Verb", "N5"],
    ["送る", "おくる", "okuru", "to send", "Verb", "N5"],
    ["手伝う", "てつだう", "tetsudau", "to help, to assist", "Verb", "N5"],
    ["急ぐ", "いそぐ", "isogu", "to hurry, to rush", "Verb", "N5"],
    ["困る", "こまる", "komaru", "to be troubled, to be in difficulty", "Verb", "N5"],
    ["始まる", "はじまる", "hajimaru", "to begin, to start (intrans.)", "Verb", "N5"],
    ["終わる", "おわる", "owaru", "to end, to finish (intrans.)", "Verb", "N5"],
    ["押す", "おす", "osu", "to push, to press", "Verb", "N5"],
    ["引く", "ひく", "hiku", "to pull, to draw", "Verb", "N5"],
    ["似る", "にる", "niru", "to resemble, to look like", "Verb", "N5"],
    ["違う", "ちがう", "chigau", "to differ, to be different", "Verb", "N5"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N4 – VERBS
  // ────────────────────────────────────────────────────────────
  verbs_n4: [
    // Change & State
    ["変わる", "かわる", "kawaru", "to change, to vary (intrans.)", "Verb", "N4"],
    ["変える", "かえる", "kaeru", "to change (something)", "Verb", "N4"],
    ["増える", "ふえる", "fueru", "to increase, to grow (intrans.)", "Verb", "N4"],
    ["増やす", "ふやす", "fuyasu", "to increase (something)", "Verb", "N4"],
    ["減る", "へる", "heru", "to decrease, to reduce (intrans.)", "Verb", "N4"],
    ["続く", "つづく", "tsuzuku", "to continue, to last (intrans.)", "Verb", "N4"],
    ["続ける", "つづける", "tsuzukeru", "to continue (something)", "Verb", "N4"],
    ["始める", "はじめる", "hajimeru", "to begin, to start (trans.)", "Verb", "N4"],
    ["終える", "おえる", "oeru", "to finish, to complete (trans.)", "Verb", "N4"],
    ["止める", "とめる", "tomeru", "to stop (something)", "Verb", "N4"],
    ["動く", "うごく", "ugoku", "to move (intrans.)", "Verb", "N4"],
    ["動かす", "うごかす", "ugokasu", "to move (something)", "Verb", "N4"],
    ["落ちる", "おちる", "ochiru", "to fall, to drop (intrans.)", "Verb", "N4"],
    ["落とす", "おとす", "otosu", "to drop, to lose", "Verb", "N4"],
    ["壊れる", "こわれる", "kowareru", "to break, to be broken (intrans.)", "Verb", "N4"],
    ["壊す", "こわす", "kowasu", "to break, to destroy (trans.)", "Verb", "N4"],
    ["開く", "あく", "aku", "to open (intrans.)", "Verb", "N4"],
    ["閉まる", "しまる", "shimaru", "to close (intrans.)", "Verb", "N4"],
    ["消える", "きえる", "kieru", "to disappear, to go out (light)", "Verb", "N4"],
    ["現れる", "あらわれる", "arawareru", "to appear, to show up", "Verb", "N4"],
    // Cognition & Communication
    ["覚える", "おぼえる", "oboeru", "to memorise, to remember", "Verb", "N4"],
    ["忘れる", "わすれる", "wasureru", "to forget", "Verb", "N4"],
    ["考える", "かんがえる", "kangaeru", "to think, to consider", "Verb", "N4"],
    ["決める", "きめる", "kimeru", "to decide", "Verb", "N4"],
    ["決まる", "きまる", "kimaru", "to be decided, to be settled", "Verb", "N4"],
    ["調べる", "しらべる", "shiraberu", "to investigate, to look up", "Verb", "N4"],
    ["比べる", "くらべる", "kuraberu", "to compare", "Verb", "N4"],
    ["信じる", "しんじる", "shinjiru", "to believe, to trust", "Verb", "N4"],
    ["相談する", "そうだんする", "soudan suru", "to consult, to discuss", "Verb", "N4"],
    ["説明する", "せつめいする", "setsumei suru", "to explain", "Verb", "N4"],
    ["紹介する", "しょうかいする", "shoukai suru", "to introduce", "Verb", "N4"],
    ["連絡する", "れんらくする", "renraku suru", "to contact, to get in touch", "Verb", "N4"],
    ["報告する", "ほうこくする", "houkoku suru", "to report", "Verb", "N4"],
    ["質問する", "しつもんする", "shitsumon suru", "to ask a question", "Verb", "N4"],
    ["返事する", "へんじする", "henji suru", "to reply, to respond", "Verb", "N4"],
    ["断る", "ことわる", "kotowaru", "to refuse, to decline, to turn down", "Verb", "N4"],
    ["頼む", "たのむ", "tanomu", "to ask, to request, to depend on", "Verb", "N4"],
    ["伝える", "つたえる", "tsutaeru", "to convey, to pass on, to tell", "Verb", "N4"],
    ["訪問する", "ほうもんする", "houmon suru", "to visit (a place or person)", "Verb", "N4"],
    ["招待する", "しょうたいする", "shoutai suru", "to invite", "Verb", "N4"],
    ["謝る", "あやまる", "ayamaru", "to apologise", "Verb", "N4"],
    ["褒める", "ほめる", "homeru", "to praise, to compliment", "Verb", "N4"],
    ["叱る", "しかる", "shikaru", "to scold, to reprimand", "Verb", "N4"],
    // Handling Objects
    ["集める", "あつめる", "atsumeru", "to collect, to gather (trans.)", "Verb", "N4"],
    ["集まる", "あつまる", "atsumaru", "to gather, to assemble (intrans.)", "Verb", "N4"],
    ["選ぶ", "えらぶ", "erabu", "to choose, to select", "Verb", "N4"],
    ["渡す", "わたす", "watasu", "to hand over, to pass, to give", "Verb", "N4"],
    ["受ける", "うける", "ukeru", "to receive, to accept, to take (exam)", "Verb", "N4"],
    ["運ぶ", "はこぶ", "hakobu", "to carry, to transport", "Verb", "N4"],
    ["拾う", "ひろう", "hirou", "to pick up, to find", "Verb", "N4"],
    ["捨てる", "すてる", "suteru", "to throw away, to discard", "Verb", "N4"],
    ["直す", "なおす", "naosu", "to fix, to repair, to correct", "Verb", "N4"],
    ["直る", "なおる", "naoru", "to be fixed, to get better (intrans.)", "Verb", "N4"],
    ["片付ける", "かたづける", "katazukeru", "to tidy up, to put away", "Verb", "N4"],
    ["準備する", "じゅんびする", "junbi suru", "to prepare, to get ready", "Verb", "N4"],
    ["確認する", "かくにんする", "kakunin suru", "to confirm, to check", "Verb", "N4"],
    ["注意する", "ちゅういする", "chuui suru", "to pay attention, to warn, to be careful", "Verb", "N4"],
    ["利用する", "りようする", "riyou suru", "to use, to make use of", "Verb", "N4"],
    ["経験する", "けいけんする", "keiken suru", "to experience", "Verb", "N4"],
    ["計画する", "けいかくする", "keikaku suru", "to plan", "Verb", "N4"],
    ["記録する", "きろくする", "kiroku suru", "to record, to document", "Verb", "N4"],
    ["予約する", "よやくする", "yoyaku suru", "to reserve, to book", "Verb", "N4"],
    ["払う", "はらう", "harau", "to pay", "Verb", "N4"],
    ["貯める", "ためる", "tameru", "to save up (money)", "Verb", "N4"],
    // Feelings & States
    ["喜ぶ", "よろこぶ", "yorokobu", "to be pleased, to be delighted", "Verb", "N4"],
    ["悲しむ", "かなしむ", "kanashimu", "to feel sad, to grieve", "Verb", "N4"],
    ["怒る", "おこる", "okoru", "to get angry", "Verb", "N4"],
    ["驚く", "おどろく", "odoroku", "to be surprised, to be astonished", "Verb", "N4"],
    ["笑う", "わらう", "warau", "to laugh, to smile", "Verb", "N4"],
    ["泣く", "なく", "naku", "to cry, to weep", "Verb", "N4"],
    ["緊張する", "きんちょうする", "kinchou suru", "to be nervous, to be tense", "Verb", "N4"],
    ["安心する", "あんしんする", "anshin suru", "to feel relieved, to be at ease", "Verb", "N4"],
    ["失望する", "しつぼうする", "shitsubou suru", "to be disappointed", "Verb", "N4"],
    ["疲れる", "つかれる", "tsukareru", "to get tired, to be exhausted", "Verb", "N4"],
    ["慣れる", "なれる", "nareru", "to get used to, to become accustomed", "Verb", "N4"],
    ["飽きる", "あきる", "akiru", "to get bored, to tire of", "Verb", "N4"],
    ["心配する", "しんぱいする", "shinpai suru", "to worry, to be concerned", "Verb", "N4"],
    ["努力する", "どりょくする", "doryoku suru", "to make an effort, to work hard", "Verb", "N4"],
    // Life Events
    ["生まれる", "うまれる", "umareru", "to be born", "Verb", "N4"],
    ["育つ", "そだつ", "sodatsu", "to grow up, to be raised", "Verb", "N4"],
    ["育てる", "そだてる", "sodateru", "to raise, to bring up, to nurture", "Verb", "N4"],
    ["結婚する", "けっこんする", "kekkon suru", "to marry, to get married", "Verb", "N4"],
    ["離婚する", "りこんする", "rikon suru", "to divorce", "Verb", "N4"],
    ["死ぬ", "しぬ", "shinu", "to die", "Verb", "N4"],
    ["助ける", "たすける", "tasukeru", "to help, to rescue, to save", "Verb", "N4"],
    ["参加する", "さんかする", "sanka suru", "to participate, to join", "Verb", "N4"],
    ["出席する", "しゅっせきする", "shusseki suru", "to attend, to be present", "Verb", "N4"],
    ["欠席する", "けっせきする", "kesseki suru", "to be absent", "Verb", "N4"],
    ["合格する", "ごうかくする", "goukaku suru", "to pass (an exam)", "Verb", "N4"],
    ["失敗する", "しっぱいする", "shippai suru", "to fail, to make a mistake", "Verb", "N4"],
    ["成功する", "せいこうする", "seikou suru", "to succeed", "Verb", "N4"],
    ["引っ越す", "ひっこす", "hikkosu", "to move (to a new home)", "Verb", "N4"],
    ["卒業する", "そつぎょうする", "sotsugyou suru", "to graduate", "Verb", "N4"],
    ["入学する", "にゅうがくする", "nyuugaku suru", "to enter school/university", "Verb", "N4"],
    ["留学する", "りゅうがくする", "ryuugaku suru", "to study abroad", "Verb", "N4"],
    // Movement & Transport
    ["泊まる", "とまる", "tomaru", "to stay overnight, to lodge", "Verb", "N4"],
    ["迎える", "むかえる", "mukaeru", "to greet, to meet, to welcome", "Verb", "N4"],
    ["見つかる", "みつかる", "mitsukaru", "to be found (intrans.)", "Verb", "N4"],
    ["見つける", "みつける", "mitsukeru", "to find (trans.)", "Verb", "N4"],
    ["起こす", "おこす", "okosu", "to wake (someone) up, to cause", "Verb", "N4"],
    ["起こる", "おこる", "okoru", "to occur, to happen", "Verb", "N4"],
    ["生きる", "いきる", "ikiru", "to live, to be alive", "Verb", "N4"],
    ["戻る", "もどる", "modoru", "to return, to go back", "Verb", "N4"],
    ["戻す", "もどす", "modosu", "to return (something), to put back", "Verb", "N4"],
    ["残る", "のこる", "nokoru", "to remain, to be left over", "Verb", "N4"],
    ["着く", "つく", "tsuku", "to arrive", "Verb", "N4"],
    ["出発する", "しゅっぱつする", "shuppatsu suru", "to depart, to set off", "Verb", "N4"],
    ["乗り換える", "のりかえる", "norikae ru", "to transfer (transport)", "Verb", "N4"],
    ["運転する", "うんてんする", "unten suru", "to drive", "Verb", "N4"],
    ["散歩する", "さんぽする", "sanpo suru", "to take a walk, to stroll", "Verb", "N4"],
    ["旅行する", "りょこうする", "ryokou suru", "to travel, to go on a trip", "Verb", "N4"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N5 – ADJECTIVES
  // ────────────────────────────────────────────────────────────
  adjectives_n5: [
    // i-Adjectives
    ["大きい", "おおきい", "ookii", "big, large", "Adjective", "N5"],
    ["小さい", "ちいさい", "chiisai", "small, little", "Adjective", "N5"],
    ["高い", "たかい", "takai", "high, tall, expensive", "Adjective", "N5"],
    ["低い", "ひくい", "hikui", "low, short (height)", "Adjective", "N5"],
    ["長い", "ながい", "nagai", "long", "Adjective", "N5"],
    ["短い", "みじかい", "mijikai", "short (length)", "Adjective", "N5"],
    ["広い", "ひろい", "hiroi", "wide, spacious, broad", "Adjective", "N5"],
    ["狭い", "せまい", "semai", "narrow, cramped", "Adjective", "N5"],
    ["多い", "おおい", "ooi", "many, a lot", "Adjective", "N5"],
    ["少ない", "すくない", "sukunai", "few, little, scarce", "Adjective", "N5"],
    ["安い", "やすい", "yasui", "cheap, inexpensive", "Adjective", "N5"],
    ["新しい", "あたらしい", "atarashii", "new", "Adjective", "N5"],
    ["古い", "ふるい", "furui", "old (thing/time)", "Adjective", "N5"],
    ["若い", "わかい", "wakai", "young", "Adjective", "N5"],
    ["良い", "よい", "yoi", "good", "Adjective", "N5"],
    ["いい", "いい", "ii", "good (casual)", "Adjective", "N5"],
    ["悪い", "わるい", "warui", "bad, wrong", "Adjective", "N5"],
    ["暑い", "あつい", "atsui", "hot (weather, room)", "Adjective", "N5"],
    ["寒い", "さむい", "samui", "cold (weather)", "Adjective", "N5"],
    ["熱い", "あつい", "atsui", "hot (to the touch)", "Adjective", "N5"],
    ["冷たい", "つめたい", "tsumetai", "cold (to the touch)", "Adjective", "N5"],
    ["温かい", "あたたかい", "atatakai", "warm", "Adjective", "N5"],
    ["涼しい", "すずしい", "suzushii", "cool (pleasantly)", "Adjective", "N5"],
    ["難しい", "むずかしい", "muzukashii", "difficult", "Adjective", "N5"],
    ["易しい", "やさしい", "yasashii", "easy (task)", "Adjective", "N5"],
    ["面白い", "おもしろい", "omoshiroi", "interesting, funny", "Adjective", "N5"],
    ["つまらない", "つまらない", "tsumaranai", "boring, dull, trivial", "Adjective", "N5"],
    ["楽しい", "たのしい", "tanoshii", "fun, enjoyable", "Adjective", "N5"],
    ["忙しい", "いそがしい", "isogashii", "busy", "Adjective", "N5"],
    ["眠い", "ねむい", "nemui", "sleepy, drowsy", "Adjective", "N5"],
    ["痛い", "いたい", "itai", "painful, sore", "Adjective", "N5"],
    ["重い", "おもい", "omoi", "heavy", "Adjective", "N5"],
    ["軽い", "かるい", "karui", "light (in weight)", "Adjective", "N5"],
    ["速い", "はやい", "hayai", "fast, quick", "Adjective", "N5"],
    ["遅い", "おそい", "osoi", "slow, late", "Adjective", "N5"],
    ["早い", "はやい", "hayai", "early", "Adjective", "N5"],
    ["丸い", "まるい", "marui", "round, circular", "Adjective", "N5"],
    ["白い", "しろい", "shiroi", "white", "Adjective", "N5"],
    ["黒い", "くろい", "kuroi", "black", "Adjective", "N5"],
    ["赤い", "あかい", "akai", "red", "Adjective", "N5"],
    ["青い", "あおい", "aoi", "blue, green (natural)", "Adjective", "N5"],
    ["黄色い", "きいろい", "kiiroi", "yellow", "Adjective", "N5"],
    ["おいしい", "おいしい", "oishii", "delicious, tasty", "Adjective", "N5"],
    ["まずい", "まずい", "mazui", "bad-tasting, unappetising", "Adjective", "N5"],
    ["辛い", "からい", "karai", "spicy, hot (taste)", "Adjective", "N5"],
    ["甘い", "あまい", "amai", "sweet", "Adjective", "N5"],
    ["すっぱい", "すっぱい", "suppai", "sour, tart", "Adjective", "N5"],
    ["近い", "ちかい", "chikai", "near, close", "Adjective", "N5"],
    ["遠い", "とおい", "tooi", "far, distant", "Adjective", "N5"],
    ["明るい", "あかるい", "akarui", "bright, cheerful", "Adjective", "N5"],
    ["暗い", "くらい", "kurai", "dark, gloomy", "Adjective", "N5"],
    ["優しい", "やさしい", "yasashii", "kind, gentle", "Adjective", "N5"],
    ["強い", "つよい", "tsuyoi", "strong, powerful", "Adjective", "N5"],
    ["弱い", "よわい", "yowai", "weak", "Adjective", "N5"],
    ["嬉しい", "うれしい", "ureshii", "happy, glad, pleased", "Adjective", "N5"],
    ["悲しい", "かなしい", "kanashii", "sad, sorrowful", "Adjective", "N5"],
    ["怖い", "こわい", "kowai", "scary, frightening", "Adjective", "N5"],
    ["恥ずかしい", "はずかしい", "hazukashii", "embarrassing, shy", "Adjective", "N5"],
    // na-Adjectives (N5)
    ["好き", "すき", "suki", "liked, favourite", "Adjective", "N5"],
    ["嫌い", "きらい", "kirai", "disliked, hated", "Adjective", "N5"],
    ["上手", "じょうず", "jouzu", "skilled, good at", "Adjective", "N5"],
    ["下手", "へた", "heta", "unskilled, bad at", "Adjective", "N5"],
    ["有名", "ゆうめい", "yuumei", "famous", "Adjective", "N5"],
    ["静か", "しずか", "shizuka", "quiet, calm", "Adjective", "N5"],
    ["にぎやか", "にぎやか", "nigiyaka", "lively, bustling", "Adjective", "N5"],
    ["きれい", "きれい", "kirei", "beautiful, clean", "Adjective", "N5"],
    ["元気", "げんき", "genki", "healthy, energetic, lively", "Adjective", "N5"],
    ["親切", "しんせつ", "shinsetsu", "kind, considerate", "Adjective", "N5"],
    ["大丈夫", "だいじょうぶ", "daijoubu", "alright, no problem", "Adjective", "N5"],
    ["大変", "たいへん", "taihen", "tough, difficult, awful", "Adjective", "N5"],
    ["暇", "ひま", "hima", "free time, not busy", "Adjective", "N5"],
    ["いや", "いや", "iya", "unpleasant, no way", "Adjective", "N5"],
    ["大切", "たいせつ", "taisetsu", "important, precious", "Adjective", "N5"],
    ["大好き", "だいすき", "daisuki", "love, really like very much", "Adjective", "N5"],
    ["大嫌い", "だいきらい", "daikirai", "hate, really dislike", "Adjective", "N5"],
    ["真面目", "まじめ", "majime", "serious, earnest, diligent", "Adjective", "N5"],
    ["丁寧", "ていねい", "teinei", "polite, careful, thorough", "Adjective", "N5"],
    ["便利", "べんり", "benri", "convenient, useful", "Adjective", "N5"],
    ["不便", "ふべん", "fuben", "inconvenient", "Adjective", "N5"],
    ["簡単", "かんたん", "kantan", "easy, simple", "Adjective", "N5"],
    ["特別", "とくべつ", "tokubetsu", "special, exceptional", "Adjective", "N5"],
    ["普通", "ふつう", "futsuu", "ordinary, normal, usual", "Adjective", "N5"],
    ["安全", "あんぜん", "anzen", "safe, secure", "Adjective", "N5"],
    ["危険", "きけん", "kiken", "dangerous, risky", "Adjective", "N5"],
    ["自由", "じゆう", "jiyuu", "free, freedom, unrestricted", "Adjective", "N5"],
    ["必要", "ひつよう", "hitsuyou", "necessary, required", "Adjective", "N5"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N4 – ADJECTIVES
  // ────────────────────────────────────────────────────────────
  adjectives_n4: [
    // i-Adjectives (N4)
    ["懐かしい", "なつかしい", "natsukashii", "nostalgic, fondly remembered", "Adjective", "N4"],
    ["珍しい", "めずらしい", "mezurashii", "rare, unusual, uncommon", "Adjective", "N4"],
    ["正しい", "ただしい", "tadashii", "correct, right, proper", "Adjective", "N4"],
    ["厳しい", "きびしい", "kibishii", "strict, harsh, severe", "Adjective", "N4"],
    ["細かい", "こまかい", "komakai", "fine, detailed, small (pieces)", "Adjective", "N4"],
    ["やわらかい", "やわらかい", "yawarakai", "soft, flexible", "Adjective", "N4"],
    ["硬い", "かたい", "katai", "hard, stiff, firm", "Adjective", "N4"],
    ["濃い", "こい", "koi", "thick (liquid/taste), dark (colour)", "Adjective", "N4"],
    ["薄い", "うすい", "usui", "thin, light (colour/taste)", "Adjective", "N4"],
    ["深い", "ふかい", "fukai", "deep", "Adjective", "N4"],
    ["浅い", "あさい", "asai", "shallow", "Adjective", "N4"],
    ["太い", "ふとい", "futoi", "thick, fat", "Adjective", "N4"],
    ["細い", "ほそい", "hosoi", "thin, slender, narrow", "Adjective", "N4"],
    ["汚い", "きたない", "kitanai", "dirty, messy, unclean", "Adjective", "N4"],
    ["うるさい", "うるさい", "urusai", "noisy, annoying, fussy", "Adjective", "N4"],
    ["欲しい", "ほしい", "hoshii", "wanted, desired", "Adjective", "N4"],
    ["惜しい", "おしい", "oshii", "a pity, regrettable, close (near miss)", "Adjective", "N4"],
    ["賢い", "かしこい", "kashikoi", "clever, wise, smart", "Adjective", "N4"],
    ["鋭い", "するどい", "surudoi", "sharp, keen, acute", "Adjective", "N4"],
    ["のろい", "のろい", "noroi", "slow (person/reaction), dull", "Adjective", "N4"],
    ["ひどい", "ひどい", "hidoi", "terrible, awful, cruel, severe", "Adjective", "N4"],
    ["激しい", "はげしい", "hageshii", "intense, violent, fierce", "Adjective", "N4"],
    ["苦い", "にがい", "nigai", "bitter (taste)", "Adjective", "N4"],
    ["臭い", "くさい", "kusai", "smelly, stinky", "Adjective", "N4"],
    ["滑らかい", "なめらかい", "namerakai", "smooth (surface/texture)", "Adjective", "N4"],
    ["怪しい", "あやしい", "ayashii", "suspicious, dubious, shady", "Adjective", "N4"],
    // na-Adjectives (N4)
    ["失礼", "しつれい", "shitsurei", "rude, discourteous, impolite", "Adjective", "N4"],
    ["幸せ", "しあわせ", "shiawase", "happy, fortunate, blessed", "Adjective", "N4"],
    ["不幸", "ふこう", "fukou", "unhappy, unfortunate", "Adjective", "N4"],
    ["健康", "けんこう", "kenkou", "healthy, in good health", "Adjective", "N4"],
    ["真剣", "しんけん", "shinken", "serious, earnest, sincere", "Adjective", "N4"],
    ["立派", "りっぱ", "rippa", "splendid, fine, impressive", "Adjective", "N4"],
    ["素直", "すなお", "sunao", "honest, obedient, meek", "Adjective", "N4"],
    ["熱心", "ねっしん", "nesshin", "enthusiastic, zealous, eager", "Adjective", "N4"],
    ["十分", "じゅうぶん", "juubun", "enough, sufficient", "Adjective", "N4"],
    ["不十分", "ふじゅうぶん", "fujuubun", "insufficient, not enough", "Adjective", "N4"],
    ["正確", "せいかく", "seikaku", "accurate, precise, correct", "Adjective", "N4"],
    ["適切", "てきせつ", "tekisetsu", "appropriate, suitable, proper", "Adjective", "N4"],
    ["不思議", "ふしぎ", "fushigi", "mysterious, strange, wonderful", "Adjective", "N4"],
    ["苦手", "にがて", "nigate", "poor at, not good at, weak point", "Adjective", "N4"],
    ["得意", "とくい", "tokui", "good at, skilled in, proud of", "Adjective", "N4"],
    ["様々", "さまざま", "samazama", "various, diverse", "Adjective", "N4"],
    ["急", "きゅう", "kyuu", "sudden, urgent, steep", "Adjective", "N4"],
    ["複雑", "ふくざつ", "fukuzatsu", "complex, complicated", "Adjective", "N4"],
    ["平和", "へいわ", "heiwa", "peaceful", "Adjective", "N4"],
    ["公平", "こうへい", "kouhei", "fair, impartial, equal", "Adjective", "N4"],
    ["不公平", "ふこうへい", "fukouhei", "unfair, unjust", "Adjective", "N4"],
    ["清潔", "せいけつ", "seiketsu", "clean, hygienic", "Adjective", "N4"],
    ["不潔", "ふけつ", "fuketsu", "unclean, dirty", "Adjective", "N4"],
    ["素敵", "すてき", "suteki", "wonderful, lovely, stylish", "Adjective", "N4"],
    ["残念", "ざんねん", "zannen", "regrettable, unfortunate, what a shame", "Adjective", "N4"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N5 – ADVERBS, CONJUNCTIONS & EXPRESSIONS
  // ────────────────────────────────────────────────────────────
  adverbs_n5: [
    // Degree & Amount
    ["とても", "とても", "totemo", "very, extremely", "Adverb", "N5"],
    ["少し", "すこし", "sukoshi", "a little, a bit", "Adverb", "N5"],
    ["ちょっと", "ちょっと", "chotto", "a little, a moment (casual)", "Adverb", "N5"],
    ["もっと", "もっと", "motto", "more, even more", "Adverb", "N5"],
    ["たくさん", "たくさん", "takusan", "a lot, many, much", "Adverb", "N5"],
    ["全部", "ぜんぶ", "zenbu", "all, everything, entirely", "Adverb", "N5"],
    ["本当に", "ほんとうに", "hontou ni", "really, truly", "Adverb", "N5"],
    ["全然", "ぜんぜん", "zenzen", "not at all (with negative)", "Adverb", "N5"],
    ["あまり", "あまり", "amari", "not very (with negative)", "Adverb", "N5"],
    // Frequency
    ["いつも", "いつも", "itsumo", "always, usually", "Adverb", "N5"],
    ["よく", "よく", "yoku", "often, well", "Adverb", "N5"],
    ["時々", "ときどき", "tokidoki", "sometimes", "Adverb", "N5"],
    ["たまに", "たまに", "tama ni", "occasionally, once in a while", "Adverb", "N5"],
    ["まだ", "まだ", "mada", "still, not yet", "Adverb", "N5"],
    ["もう", "もう", "mou", "already, anymore", "Adverb", "N5"],
    ["また", "また", "mata", "again, also, and", "Adverb", "N5"],
    // Sequence & Order
    ["まず", "まず", "mazu", "first of all, to begin with", "Adverb", "N5"],
    ["次に", "つぎに", "tsugi ni", "next, then", "Adverb", "N5"],
    ["最後に", "さいごに", "saigo ni", "lastly, finally", "Adverb", "N5"],
    ["一緒に", "いっしょに", "issho ni", "together", "Adverb", "N5"],
    // Manner
    ["ゆっくり", "ゆっくり", "yukkuri", "slowly, leisurely, at one's ease", "Adverb", "N5"],
    ["はっきり", "はっきり", "hakkiri", "clearly, distinctly", "Adverb", "N5"],
    ["すぐ", "すぐ", "sugu", "immediately, right away, soon", "Adverb", "N5"],
    // Conjunctions
    ["そして", "そして", "soshite", "and (then), and also", "Conjunction", "N5"],
    ["でも", "でも", "demo", "but, however", "Conjunction", "N5"],
    ["だから", "だから", "dakara", "therefore, so, that is why", "Conjunction", "N5"],
    ["それから", "それから", "sore kara", "after that, and then", "Conjunction", "N5"],
    ["それで", "それで", "sore de", "so, because of that, and then", "Conjunction", "N5"],
    ["けど", "けど", "kedo", "but, though (casual)", "Conjunction", "N5"],
    // Expressions
    ["どうぞ", "どうぞ", "douzo", "please (offering), go ahead", "Expression", "N5"],
    ["ありがとう", "ありがとう", "arigatou", "thank you", "Expression", "N5"],
    ["すみません", "すみません", "sumimasen", "excuse me, I am sorry", "Expression", "N5"],
    ["ごめんなさい", "ごめんなさい", "gomen nasai", "I am sorry (apology)", "Expression", "N5"],
    ["はい", "はい", "hai", "yes, I understand", "Expression", "N5"],
    ["いいえ", "いいえ", "iie", "no", "Expression", "N5"],
    ["おはようございます", "おはようございます", "ohayou gozaimasu", "good morning (polite)", "Expression", "N5"],
    ["こんにちは", "こんにちは", "konnichiwa", "hello, good afternoon", "Expression", "N5"],
    ["こんばんは", "こんばんは", "konbanwa", "good evening", "Expression", "N5"],
    ["おやすみなさい", "おやすみなさい", "oyasumi nasai", "good night", "Expression", "N5"],
    ["さようなら", "さようなら", "sayounara", "goodbye", "Expression", "N5"],
    ["じゃあ", "じゃあ", "jaa", "well then, see you (casual)", "Expression", "N5"],
    ["いただきます", "いただきます", "itadakimasu", "expression before eating", "Expression", "N5"],
    ["ごちそうさまでした", "ごちそうさまでした", "gochisousama deshita", "expression after eating", "Expression", "N5"],
    ["よろしくお願いします", "よろしくおねがいします", "yoroshiku onegaishimasu", "pleased to meet you, I am in your care", "Expression", "N5"],
    ["はじめまして", "はじめまして", "hajimemashite", "nice to meet you (first time)", "Expression", "N5"],
    ["どういたしまして", "どういたしまして", "dou itashimashite", "you are welcome, don't mention it", "Expression", "N5"],
  ],

  // ────────────────────────────────────────────────────────────
  //  N4 – ADVERBS, CONJUNCTIONS & EXPRESSIONS
  // ────────────────────────────────────────────────────────────
  adverbs_n4: [
    // Degree & Amount
    ["だいたい", "だいたい", "daitai", "roughly, approximately, generally", "Adverb", "N4"],
    ["ほとんど", "ほとんど", "hotondo", "almost, mostly, nearly", "Adverb", "N4"],
    ["かなり", "かなり", "kanari", "considerably, quite, fairly", "Adverb", "N4"],
    ["ずいぶん", "ずいぶん", "zuibun", "considerably, really, quite", "Adverb", "N4"],
    ["なかなか", "なかなか", "nakanaka", "considerably / not easily (negative)", "Adverb", "N4"],
    ["十分に", "じゅうぶんに", "juubun ni", "sufficiently, enough", "Adverb", "N4"],
    // Frequency & Time
    ["特に", "とくに", "toku ni", "especially, particularly, in particular", "Adverb", "N4"],
    ["最近", "さいきん", "saikin", "recently, lately, these days", "Adverb", "N4"],
    ["以前", "いぜん", "izen", "before, previously, formerly", "Adverb", "N4"],
    ["以後", "いご", "igo", "after this, from now on, since then", "Adverb", "N4"],
    ["最初", "さいしょ", "saisho", "first, the beginning, at first", "Adverb", "N4"],
    ["最後", "さいご", "saigo", "last, the end, finally", "Adverb", "N4"],
    ["やっと", "やっと", "yatto", "finally, at last", "Adverb", "N4"],
    ["もうすぐ", "もうすぐ", "mou sugu", "very soon, before long", "Adverb", "N4"],
    ["だんだん", "だんだん", "dandan", "gradually, little by little", "Adverb", "N4"],
    ["どんどん", "どんどん", "dondon", "rapidly, progressively, one after another", "Adverb", "N4"],
    ["急に", "きゅうに", "kyuu ni", "suddenly, all of a sudden", "Adverb", "N4"],
    ["いつか", "いつか", "itsuka", "sometime, someday, one day", "Adverb", "N4"],
    ["なるべく", "なるべく", "narubeku", "as much as possible, if possible", "Adverb", "N4"],
    ["できるだけ", "できるだけ", "dekiru dake", "as much as possible", "Adverb", "N4"],
    ["ちゃんと", "ちゃんと", "chanto", "properly, correctly, neatly", "Adverb", "N4"],
    ["きっと", "きっと", "kitto", "surely, certainly, definitely", "Adverb", "N4"],
    ["たぶん", "たぶん", "tabun", "probably, perhaps, maybe", "Adverb", "N4"],
    ["もちろん", "もちろん", "mochiron", "of course, certainly, naturally", "Adverb", "N4"],
    ["ぜひ", "ぜひ", "zehi", "by all means, definitely, please (do)", "Adverb", "N4"],
    ["わざわざ", "わざわざ", "wazawaza", "going out of one's way to, especially", "Adverb", "N4"],
    ["やはり", "やはり", "yahari", "as expected, after all, still", "Adverb", "N4"],
    ["やっぱり", "やっぱり", "yappari", "as I thought, after all (casual)", "Adverb", "N4"],
    ["しかも", "しかも", "shikamo", "moreover, furthermore, and yet", "Adverb", "N4"],
    ["ところで", "ところで", "tokoro de", "by the way", "Adverb", "N4"],
    // Conjunctions
    ["たとえば", "たとえば", "tatoeba", "for example, for instance", "Conjunction", "N4"],
    ["それに", "それに", "sore ni", "besides, moreover, in addition", "Conjunction", "N4"],
    ["しかし", "しかし", "shikashi", "however, but", "Conjunction", "N4"],
    ["それでも", "それでも", "soredemo", "even so, nevertheless", "Conjunction", "N4"],
    ["したがって", "したがって", "shitagatte", "therefore, accordingly, consequently", "Conjunction", "N4"],
    ["つまり", "つまり", "tsumari", "in other words, that is to say, namely", "Conjunction", "N4"],
    ["ところが", "ところが", "tokoro ga", "however, but (unexpectedly)", "Conjunction", "N4"],
    ["なぜなら", "なぜなら", "nazenara", "because, the reason is", "Conjunction", "N4"],
    ["一方", "いっぽう", "ippou", "on the other hand, meanwhile", "Conjunction", "N4"],
    ["あるいは", "あるいは", "aruiwa", "or, either ... or, perhaps", "Conjunction", "N4"],
    ["ただし", "ただし", "tadashi", "however, but, provided that", "Conjunction", "N4"],
    ["もし", "もし", "moshi", "if, in case (hypothetical)", "Conjunction", "N4"],
    ["たとえ", "たとえ", "tatoe", "even if, even though", "Conjunction", "N4"],
    // Expressions (N4)
    ["失礼しました", "しつれいしました", "shitsurei shimashita", "I beg your pardon, excuse me (past/apology)", "Expression", "N4"],
    ["おかげさまで", "おかげさまで", "okage sama de", "thanks to you, I am fine (response)", "Expression", "N4"],
    ["さすが", "さすが", "sasuga", "as expected, just as one would expect", "Expression", "N4"],
    ["いかがですか", "いかがですか", "ikaga desu ka", "how about ...? how is ...? (polite)", "Expression", "N4"],
  ],
};

module.exports = vocabulary;
